name: EVCC (pinned 0.207.4)
version: "0.207.4-ha1"
slug: evcc_pinned
description: EVCC figé sur l'image Docker evcc/evcc:0.207.4
url: https://github.com/evcc-io/evcc
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
ingress: false
panel_icon: mdi:ev-station
watchdog: true
image: "evcc/evcc:0.207.4"
map:
  - config:rw
ports:
  "7070/tcp": 7070
webui: "http://[HOST]:[PORT:7070]"
command:
  - "-c"
  - "/config/evcc.yaml"
schema: {}
